- Entity:
    id: http://www.purl.org/ogit/Forum/Configuration
    name: Configuration
    description: |
      Configuration Data. No Schema - all free attributes
    valid-from: 2015-04-23
    valid-until: 
    creator: cwalker@arago.de
    deleter: 
    created: 2015-04-23
    modified: 2015-04-23
    admin-contact: arago GmbH
    tech-contact: arago GmbH
    scope: NTO
    parent: http://www.purl.org/ogit/Node
    attributes:
      mandatory:
        - 
      optional:
        - 
    history:
      - id: 1
        date: 2015-04-25
        description: Initial Creation
        modified-by: cwalker@arago.de

